scripts/create-makefile.sh: add -I flag for toplevel directory to ccflags-y
Since upstream commit 58156ba4468f ("kbuild: skip 'addtree' and 'flags'
magic for external module build") Kbuild won't add an -I flag for an
external module's toplevel source directory to the compilation flags
anymore.

This results in compilation errors like the following:

  uname_patch/livepatch_uname.c:36:10: fatal error: klp_convert.h: No such
                                                    file or directory
  #include "klp_convert.h"
           ^~~~~~~~~~~~~~~

Fix this by appending '-I$(obj)' to ccflags-y within the Makefile created
by scripts/create-makefile.sh. Note that "$(obj)" is set to the current
source directory before the Makefile is sourced by Kbuild.

Signed-off-by: Nicolai Stange <nstange@suse.de>